const Actions ={

ADMINLOGIN:'ADMINLOGIN',
ADMINLOGINSUCCESS:'ADMINLOGINSUCCESS',
ADMINLOGINFAILED:'ADMINLOGINFAILED',


STOREREQUEST:'STOREREQUEST',
STOREREQUESTSUCCESS:'STOREREQUESTSUCCESS',
STOREREQUESTFAILED:'STOREREQUESTFAILED',


ADDPRODUCTREQUEST:'ADDPRODUCTREQUEST',
ADDPRODUCTREQUESTSUCCESS:'ADDPRODUCTREQUESTSUCCESS',
ADDPRODUCTREQUESTFAILED:'ADDPRODUCTREQUESTFAILED'

}


export default Actions;