const Actions ={

ADMINLOGIN:'ADMINLOGIN',
ADMINLOGINSUCCESS:'ADMINLOGINSUCCESS',
ADMINLOGINFAILED:'ADMINLOGINFAILED',


STOREREQUEST:'STOREREQUEST',
STOREREQUESTSUCCESS:'STOREREQUESTSUCCESS',
STOREREQUESTFAILED:'STOREREQUESTFAILED',


ADDPRODUCTREQUEST:'ADDPRODUCTREQUEST',
ADDPRODUCTREQUESTSUCCESS:'ADDPRODUCTREQUESTSUCCESS',
ADDPRODUCTREQUESTFAILED:'ADDPRODUCTREQUESTFAILED',

storeData : 'storeData',
storeDataSuccess : 'storeDataSuccess',
ProductData:'ProductData',
ProductDataSuccess:'ProductDataSuccess',

ADDSALEREQUEST:'ADDSALEREQUEST',
ADDSALEREQUESTSUCCESS:'ADDSALEREQUESTSUCCESS',
ADDSALEREQUESTFAILED:'ADDSALEREQUESTFAILED',



ADDPURCHASEREQUEST:'ADDPURCHASEREQUEST',
ADDPURCHASEREQUESTSUCCESS:'ADDPURCHASEREQUESTSUCCESS',
ADDPURCHASEREQUESTFAILED:'ADDPURCHASEREQUESTFAILED',

VIEWSALE:'VIEWSALE',
VIEWSALESUCCESS:'VIEWSALESUCCESS',
VIEWSALEFAILED:'VIEWSALEFAILED',
VIEWPURCHASE:'VIEWPURCHASE',
VIEWPURCHASESUCCESS:'VIEWPURCHASESUCCESS',
VIEWPURCHASEFAILED:'VIEWPURCHASEFAILED',
}


export default Actions;